USE [master]
GO

/****** Object:  Database [DbAccessExample]    Script Date: 12.05.17 11:19:30 ******/
CREATE DATABASE [DbAccessExample]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DbAccessExample', FILENAME = N'C:\Databases\MSSQL13.MSSQLSERVER\MSSQL\DATA\DbAccessExample.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DbAccessExample_log', FILENAME = N'C:\Databases\MSSQL13.MSSQLSERVER\MSSQL\DATA\DbAccessExample_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DbAccessExample] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DbAccessExample].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DbAccessExample] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DbAccessExample] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DbAccessExample] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DbAccessExample] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DbAccessExample] SET ARITHABORT OFF 
GO

ALTER DATABASE [DbAccessExample] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DbAccessExample] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DbAccessExample] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DbAccessExample] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DbAccessExample] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DbAccessExample] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DbAccessExample] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DbAccessExample] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DbAccessExample] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DbAccessExample] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DbAccessExample] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DbAccessExample] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DbAccessExample] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DbAccessExample] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DbAccessExample] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DbAccessExample] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DbAccessExample] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DbAccessExample] SET RECOVERY FULL 
GO

ALTER DATABASE [DbAccessExample] SET  MULTI_USER 
GO

ALTER DATABASE [DbAccessExample] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DbAccessExample] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DbAccessExample] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DbAccessExample] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DbAccessExample] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DbAccessExample] SET QUERY_STORE = OFF
GO

USE [DbAccessExample]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DbAccessExample] SET  READ_WRITE 
GO

if not exists (select loginname from master.dbo.syslogins where name = 'DbAccessExample' and dbname = 'master')
	CREATE LOGIN DbAccessExample WITH PASSWORD = 'DbAccessExample'

CREATE USER DbAccessExample FROM LOGIN DbAccessExample
EXEC sp_addrolemember N'db_owner', N'DbAccessExample'